import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import localFont from "next/font/local";

import {TRPCProvider} from "@/trpc/client";
import {Providers} from "@/components/providers";
import "./globals.css";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400"],
});

export const nevanRus = localFont({
  src: "../app/fonts/nevanRus.woff2",
  variable: "--font-nevan",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nevanRus.variable} ${roboto.variable} antialiased`}>
        <TRPCProvider>
          <Providers />
          {children}
        </TRPCProvider>
      </body>
    </html>
  );
}
