export const AUTH_COOKIE = "fithub-session";

export const APPWRITE_ENDPOINT = process.env.NEXT_PUBLIC_APPWRITE_ENDPOINT!;
export const APPWRITE_PROJECT = process.env.NEXT_PUBLIC_APPWRITE_PROJECT!;
export const APPWRITE_DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE!;
export const APPWRITE_BUCKET_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_ID!;

export const APPWRITE_CLIENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_CLIENTS!;
export const APPWRITE_MEDIA_ID = process.env.NEXT_PUBLIC_APPWRITE_MEDIA_ID!;
export const APPWRITE_MENUS_ID = process.env.NEXT_PUBLIC_APPWRITE_MENUS_ID!;
export const APPWRITE_DIETS_ID = process.env.NEXT_PUBLIC_APPWRITE_DIETS_ID!;
export const APPWRITE_EXERCISES_ID = process.env.NEXT_PUBLIC_APPWRITE_EXERCISES_ID!;
export const APPWRITE_PROGRAMS_ID = process.env.NEXT_PUBLIC_APPWRITE_PROGRAMS_ID!;
export const APPWRITE_DOCUMENTS_ID = process.env.NEXT_PUBLIC_APPWRITE_DOCUMENTS_ID!;
export const APPWRITE_PAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_PAGES_ID!;
